name: Run Laravel Migration and Seed to Supabase

on:
  workflow_dispatch:

jobs:
  laravel-migration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup PHP Engine
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: pdo, pdo_pgsql, pgsql

    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Execute Artisan Migrate & Seeder
      env:
        DB_CONNECTION: pgsql
        # MATCH SINKRON: Pake Host, Port, dan Username jalur Pooler Supabase pak!
        DB_HOST: aws-0-ap-southeast-1.pooler.supabase.com # <--- Ganti sesuai dashboard lu
        DB_PORT: 6543 # <--- Wajib 6543
        DB_DATABASE: postgres
        DB_USERNAME: postgres.maxnxsxizgyemuhstyyv # <--- Ganti sesuai username pooler lu
        DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      run: php artisan migrate --force --seed